server:
  port: 8081

spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/collab_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Hibernate will build 'users' table in Postgres
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

services:
  docservice:
    baseUrl: http://localhost:8082

internal:
  secret: INTERNAL_DELETE_SECRET_123